--DROP TABLE IF EXISTS as141220.COLLECTION;
CREATE TABLE as141220.COLLECTION(
    Collection_id INT,
    Collection_name VARCHAR(64),
    Collection_type VARCHAR(9),
    Owner_id INT,
    CONSTRAINT PK_COLLECTION_COLLECTION_ID PRIMARY KEY (Collection_id),
    CONSTRAINT FK_COLLECTION_OWNER_ID_AGENT_AGENT_ID FOREIGN KEY (Owner_id) REFERENCES as141220.AGENT (Agent_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
