--DROP TABLE IF EXISTS as141220.COMPONENT;
CREATE TABLE as141220.COMPONENT(
    Component_id INT,
    Component_name VARCHAR(64),
    Component_type VARCHAR(10) NOT NULL,
    CONSTRAINT PK_COMPONENT_COMPONENT_ID PRIMARY KEY (Component_id)
);
