--DROP TABLE IF EXISTS as141220.[CONTAINS];
CREATE TABLE as141220.[CONTAINS](
    Collection_id INT,
    Recipe_id INT,
    Time_added DATETIME DEFAULT CURRENT_TIMESTAMP,
    Rank INT NOT NULL DEFAULT -1,
    Note VARCHAR(256) NOT NULL DEFAULT '',
    CONSTRAINT PK_CONTAINS_COLLECTION_ID_RECIPE_ID_TIME_ADDED PRIMARY KEY (Collection_id, Recipe_id, Time_added),
    CONSTRAINT FK_CONTAINS_COLLECTION_ID_COLLECTION_COLLECTION_ID FOREIGN KEY (Collection_id) REFERENCES as141220.COLLECTION (Collection_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CONTAINS_RECIPE_ID_RECIPE_RECIPE_ID FOREIGN KEY (Recipe_id) REFERENCES as141220.RECIPE (Recipe_id)
    ON DELETE NO ACTION ON UPDATE NO ACTION, -- Would like to CASCADE here, but could create multiple cascade paths, so need to deal with this at the application level
);
