--DROP TABLE IF EXISTS as141220.IMPLEMENT;
CREATE TABLE as141220.IMPLEMENT(
    Implement_id INT,
    Implement_type VARCHAR(64),
    CONSTRAINT PK_IMPLEMENT_IMPLEMENT_ID PRIMARY KEY (Implement_id),
    CONSTRAINT FK_IMPLEMENT_IMPLEMENT_ID_COMPONENT_COMPONENT_ID FOREIGN KEY (Implement_id) REFERENCES as141220.COMPONENT (Component_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
