--DROP TABLE IF EXISTS as141220.INGREDIENT;
CREATE TABLE as141220.INGREDIENT(
    Ingredient_id INT,
    Ingredient_type VARCHAR(64),
    CONSTRAINT PK_INGREDIENT_INGREDIENT_ID PRIMARY KEY (Ingredient_id),
    CONSTRAINT FK_INGREDIENT_INGREDIENT_ID_COMPONENT_COMPONENT_ID FOREIGN KEY (Ingredient_id) REFERENCES as141220.COMPONENT (Component_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
