--DROP TABLE IF EXISTS as141220.STEP;
CREATE TABLE as141220.STEP(
    Step_id INT,
    [Action] VARCHAR(64) NOT NULL,
    Duration VARCHAR(64) NOT NULL DEFAULT '0',
    CONSTRAINT PK_STEP_STEP_ID PRIMARY KEY (Step_id),
    CONSTRAINT UNIQUE_STEP_ACTION_DURATION UNIQUE ([Action], Duration)
);
