--DROP TABLE IF EXISTS as141220.TAG;
CREATE TABLE as141220.TAG(
    Tag_id INT,
    Tag_type VARCHAR(11) NOT NULL,
    Tag_name VARCHAR(64) NOT NULL,
    Tag_detail VARCHAR(64) NOT NULL DEFAULT '',
    CONSTRAINT PK_TAG_TAG_ID PRIMARY KEY (Tag_id)
);
