--DROP TABLE IF EXISTS as141220.[USER];
CREATE TABLE as141220.[USER](
    User_id INT,
    First_name VARCHAR(64),
    Last_name VARCHAR(64),
    Email VARCHAR(64),
    CONSTRAINT PK_USER_USER_ID PRIMARY KEY (User_id),
    CONSTRAINT FK_USER_USER_ID_AGENT_AGENT_ID FOREIGN KEY (User_id) REFERENCES as141220.AGENT (Agent_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
