--DROP TABLE IF EXISTS as141220.VIEWERSHIP;
CREATE TABLE as141220.VIEWERSHIP(
    Collection_id INT,
    Viewer_id INT,
    CONSTRAINT PK_VIEWERSHIP_COLLECTION_ID_VIEWER_ID PRIMARY KEY (Collection_id, Viewer_id),
    CONSTRAINT FK_VIEWERSHIP_COLLECTION_ID_COLLECTION_COLLECTION_ID FOREIGN KEY (Collection_id) REFERENCES as141220.COLLECTION (Collection_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_VIEWERSHIP_VIEWER_ID_AGENT_AGENT_ID FOREIGN KEY (Viewer_id) REFERENCES as141220.AGENT (Agent_id)
    ON DELETE NO ACTION ON UPDATE NO ACTION -- Would like to CASCADE here, but could create multiple cascade paths, so need to deal with this at the application level
);
